name: smb-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - pandas
  - scipy
  - seaborn
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - # add pip-only packages here if needed
